### ISSUE TITLE
Prevent accidental nags

### ISSUE THREAD

**Issue by BerglundDaniel** [makerspace/BoxTerminator-App#1]
It is currently easy to accidentally nag someone twice. It would be useful if nagging was locked out for a period after a nag has been sent.

**Comment by emanuelen5** [comment]
Ett enkelt sätt att lösa det på tänker jag är att man först skannar alla lådor och sedan skickar mail när man sammanställt listan på lådor som gått ut. Då kan man skanna lådorna snabbare dessutom när man inte behöver knappa massa på skärmen under tiden.

**Comment by BerglundDaniel** [comment]
Det låter som den smidigaste lösningen, bonus vore också om den kunde mejla den listan till info adressen eller spara den på något annat bra sätt
